# Generated by Django 4.2.13 on 2024-05-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
